# Python File Handling: Create, Open, Append, Read, Write

## How to Create a Text File

To open a file, you need to use the built-in open function. The open function returns a file object that contains methods and attributes to perform various operations on the file.

file_object  = open("filename", "mode") 

In [33]:
file = open("text.txt","w+")

1st argument: The filename

2nd argument: The operation/permissions to the file

w: Creates a file

w+: Creates a readable file

In [34]:
for i in range(10):
    file.write('This is line %d\n' %(i+1))
    # This is line display integer, next line

file.close() 

Using the write function to enter data into the file. Be very careful to notice that the write method takes one parameter, a string. When invoked, the characters of the string will be added to the end of the file. This means that it is the programmers job to include the newline characters as part of the string if desired.

## Assess Filepath

If a file is not in the same folder as your python program, you need to tell the computer how to reach it. 

A relative file path starts from the folder that contains your python program and follows a computer’s file hierarchy. A file hierarchy contains folders which contains files and other sub-folders. Specifying a sub-folder is easy – you simply specify the sub-folder’s name. 

To specify a parent folder you use the special .. notation because every file and folder has one unique parent. You can use the .. notation multiple times in a file path to move multiple levels up a file hierarchy. 

Here is an example file hierarchy that contains multiple folders, files, and sub-folders. Folders in the diagram are displayed in bold type.

https://runestone.academy/runestone/books/published/thinkcspy/_images/ExampleFileHierarchy.png

Using the example file hierarchy above, the program, myPythonProgram.py could access each of the data files using the following relative file paths:

data1.txt
Since they have the same paths

../myData/data2.txt

../myData/data3.txt

../../otherFiles/extraData/data4.txt

## Append Data to File

Once again if you could see a plus sign in the code, it indicates that it will create a new file if it does not exist with read & write permissions

a: Append to existing file

a+: Appends to a new file





In [35]:
file2 = open("text.txt","a")

for i in range(11,21):
    file2.write('This appended line %d\n' %(i))

file2.close() 

##  Read a File

You can read a file in Python by calling .txt file in a "read mode"(r).

Use the read function to read the ENTIRE contents of a file as it is
read(n) to reads and return a string of n characters, or the entire file as a single string if n is not provided.
Unless you do a for loop, which puts each line into a string

Use readline to read one line from the file as a string which will contain the \n at the end too. Returns the empty string if it reaches the end of the file
readline(n) returns the next line of the file with all text up to and including the newline character. If n is provided as a parameter than only n characters will be returned if the line is longer than n.


Use the readlines function to read the content of the entire file one by one as a list of strings. 
readlines(n) returns a list of strings, each representing a single line of the file. If n is not provided then all lines of the file are returned. If n is provided then n characters are read but n is rounded up so that an entire line is returned.



In [47]:
file3 =open("text.txt", "r")
if file3.mode == 'r': #to check if it is indeed open, then the bottom code will run
    contents = file3.read()
    print(contents)
    

This is line 1
This is line 2
This is line 3
This is line 4
This is line 5
This is line 6
This is line 7
This is line 8
This is line 9
This is line 10
This appended line 11
This appended line 12
This appended line 13
This appended line 14
This appended line 15
This appended line 16
This appended line 17
This appended line 18
This appended line 19
This appended line 20



In [48]:
file3 =open("text.txt", "r")
if file3.mode == 'r': #to check if it is indeed open, then the bottom code will run
    content = file3.read(7)
    print(content)

This is


In [50]:
file3 =open("text.txt", "r")

contents = file3.readlines() #puts the characters of each line to a string including \n
print(contents)
    
for lines in contents: #iterate over list \n displayed out too
    print(lines)

['This is line 1\n', 'This is line 2\n', 'This is line 3\n', 'This is line 4\n', 'This is line 5\n', 'This is line 6\n', 'This is line 7\n', 'This is line 8\n', 'This is line 9\n', 'This is line 10\n', 'This appended line 11\n', 'This appended line 12\n', 'This appended line 13\n', 'This appended line 14\n', 'This appended line 15\n', 'This appended line 16\n', 'This appended line 17\n', 'This appended line 18\n', 'This appended line 19\n', 'This appended line 20\n']
This is line 1

This is line 2

This is line 3

This is line 4

This is line 5

This is line 6

This is line 7

This is line 8

This is line 9

This is line 10

This appended line 11

This appended line 12

This appended line 13

This appended line 14

This appended line 15

This appended line 16

This appended line 17

This appended line 18

This appended line 19

This appended line 20



In [2]:
file4 =open("text.txt", "r")
for lines in file4:
    values = lines.split(' ')
    values = lines.split('\n')
    #printe([values[0]])
    print (values)
file4.close()

['This is line 1', '']
['This is line 2', '']
['This is line 3', '']
['This is line 4', '']
['This is line 5', '']
['This is line 6', '']
['This is line 7', '']
['This is line 8', '']
['This is line 9', '']
['This is line 10', '']
['This appended line 11', '']
['This appended line 12', '']
['This appended line 13', '']
['This appended line 14', '']
['This appended line 15', '']
['This appended line 16', '']
['This appended line 17', '']
['This appended line 18', '']
['This appended line 19', '']
['This appended line 20', '']


## With Statements

Forgetting to close a file does not necessarily cause a runtime error in the kinds of programs you typically write in an introductory CS course.

The context manager automates the process of doing common operations at the start of some task, as well as automating certain operations at the end of some task. In the context of reading and writing a file, the normal operation is to open the file and assign it to a variable. At the end of working with a file the common operation is to make sure that file is closed.

The Python with statement makes using context managers easy. The general form of a with statement is:

When the program exits the with block, the context manager handles the common stuff that normally happens. For example closing a file. A simple example will clear up all of this abstract discussion of contexts.

In [ ]:
with <create some object that understands context> as <some name>:
    do some stuff with the object
    ...

In [70]:
with open('text.txt','r') as file:
    for line in file:
        print(line)

This is line 1

This is line 2

This is line 3

This is line 4

This is line 5

This is line 6

This is line 7

This is line 8

This is line 9

This is line 10

This appended line 11

This appended line 12

This appended line 13

This appended line 14

This appended line 15

This appended line 16

This appended line 17

This appended line 18

This appended line 19

This appended line 20



# ZIP function

In [108]:
a = [1,2,3,4,5]
b = [6,7,8,8,9]

for x,y in zip(a,b):
    print(x,y)

print(x)

1 6
2 7
3 8
4 8
5 9
5


Zip is an interable object that returns a tuple

In [112]:
a = [1,2,3,4,5]
b = [6,7,8,8,9]

[print (x,y) for x,y in zip(a,b)]
print(x)

1 6
2 7
3 8
4 8
5 9
5


In [106]:
print (zip(a,b))
for i in zip(a,b):
    print(i)
    

(1, 6)
(2, 7)
(3, 8)
(4, 8)
(5, 9)


Zip object can be turned into list

In [98]:
print(list(zip(a,b)))

[(1, 6), (2, 7), (3, 8), (4, 8), (5, 9)]


Zip object can be turned into dict only for 2 parameters

In [99]:
print(dict(zip(a,b)))

{1: 6, 2: 7, 3: 8, 4: 8, 5: 9}


# EXCEPTION 



In [128]:
try:
    f = open('text.txt') #file exists for this case
    print(O) 
except FileNotFoundError:
    print('Sorry. This file does not exist')
except NameError:
    print('The error is a Name error')
except Exception:
    print('Sorry. This file does not exist')    

The error is a Name error


Exception is general. Or we can specify the type of error to exception. Then again, always write the specific once first. Then prints out the custom error

In [131]:
try:
    f = open('text3.txt')
except FileNotFoundError as e:
    print(e)


[Errno 2] No such file or directory: 'text3.txt'


In [132]:
try:
    f = open('text.txt')
except FileNotFoundError as e:
    print(e)
else:
    print(f.read())
    f.close()

This is line 1
This is line 2
This is line 3
This is line 4
This is line 5
This is line 6
This is line 7
This is line 8
This is line 9
This is line 10
This appended line 11
This appended line 12
This appended line 13
This appended line 14
This appended line 15
This appended line 16
This appended line 17
This appended line 18
This appended line 19
This appended line 20



So python will run the code under the try block, if there is an error in any of the exception block, it will print the error.
Else it will run the code under the else block

In [134]:
try:
    f = open('text3.txt')
except FileNotFoundError as e:
    print(e)
finally:
    print('this code line still runs')

[Errno 2] No such file or directory: 'text3.txt'
this code line still runs


In [135]:
try:
    f = open('text3.txt')
except FileNotFoundError as e:
    print(e)
else:
    print('this code line still runs')

[Errno 2] No such file or directory: 'text3.txt'


Finally ensures that the code under the finally statement still runs

In [142]:
try:
    f = open('text.txt')
    if f.name == 'text.txt':
        raise Exception
except Exception as e:
    print('ERROR!')
else:
    print('this code line still runs')

ERROR!


Manually raising an error even if there isnt one

# Enumerate

In [145]:
example = ['left','right','up','down']

for i in range (len(example)):
    print(i,example[i])

0 left
1 right
2 up
3 down


In [4]:
example = ['left','right','up','down']

for j,i in enumerate(example):
    print(j,i)

0 left
1 right
2 up
3 down


In [149]:
new_dict = dict(enumerate(example))
print(new_dict)

{0: 'left', 1: 'right', 2: 'up', 3: 'down'}


In [150]:
[print(i,j) for i,j in enumerate(new_dict)]

0 0
1 1
2 2
3 3


[None, None, None, None]

## Iter
Return value from iter()
The iter() function returns an iterator object for the given object.
If the user-defined object doesn't implement __iter__(), and __next__() or __getitem()__, the TypeError exception is raised.
If the sentinel parameter is also provided, iter() returns an iterator until the sentinel character isn't foun

In [1]:
# list of vowels
vowels = ['a', 'e', 'i', 'o', 'u']
vowels_iter = iter(vowels)

print(next(vowels_iter))    # 'a'
print(next(vowels_iter))    # 'e'
print(next(vowels_iter))    # 'i'
print(next(vowels_iter))    # 'o'
print(next(vowels_iter))    # 'u'

a
e
i
o
u


# Understanding dimensions, axis in mumpy (same in tensor)

In [15]:
import numpy as np
#1D
A = np.array([1,2,3,4])
print(A.ndim) 
print(A.shape)
#row by col

np.mean(A,axis=0) 
#axis = 0, row wise

1
(4,)


2.5

In [18]:
#2D
A = np.array([[1,2,3,4],
              [3,4,5,6]])
print(A.ndim)
print(A.shape)
#row by col

print(np.mean(A,axis=0))
print(np.mean(A,axis=1))
#axis = 0, col wise
#axis = 1, row wise

2
(2, 4)
[2. 3. 4. 5.]
[2.5 4.5]


In [20]:
#3D
A = np.array([[[1,2,3],[2,3,4]],
             [[4,5,6],[6,7,8]]])
print(A.ndim)
print(A.shape)
#depth by row by col

print(np.mean(A,axis=0))
print(np.mean(A,axis=1))
print(np.mean(A,axis=2))
#axis = 0, depth wise
#axis = 1, row wise
#axis = 2, col wise

3
(2, 2, 3)
[[2.5 3.5 4.5]
 [4.  5.  6. ]]
[[1.5 2.5 3.5]
 [5.  6.  7. ]]
[[2. 3.]
 [5. 7.]]
